quantized_model_prefix = "quantized"
"""
``quantized_model_prefix`` is the file name prefix for the quantized saved model file.

The quantized saved model file's suffix is ``.tflite``. The quantized saved model file
is generated by :func:`.quantize_model`, and read by all inference implementations. It
contains the trained model's weights, biases, and quantization metadata.

:func:`.quantize_model` also saves the quantized weights, biases, and quantization
metadata to a NumPy ``.npz`` file, which is easier to work with than the ``.tflite``
file. The ``.npz`` file can be loaded with :class:`.SavedTensors`.
"""

test_data_file = "mnist_test_data.npz"
"""
Name of the ``.npz`` file containing resized MNIST test image data and the corresponding
labels.

This file is written by :func:`.save_mnist_data` and loaded by :func:`.load_mnist_data`.
Loading this file is much faster than importing `tensorflow` and re-sizing the MNIST
test data with :func:`.load_mnist_images`.
"""
