"""
``quantized_model_prefix`` is the file name prefix for the quantized saved model file.

The quantized saved model file's suffix is ``.tflite``. The quantized saved model file
is generated by :func:`.quantize_model`, and read by all inference implementations. It
contains the trained model's weights, biases, and quantization metadata.

:func:`.quantize_model` also saves the quantized weights, biases, and quantization
metadata to a NumPy ``.npz`` file, which is easier to work with than the ``.tflite``
file. The ``.npz`` file can be loaded with :class:`.SavedTensors`.
"""

quantized_model_prefix = "quantized"
